# Generated by Django 2.0.3 on 2018-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_journey', models.TextField()),
                ('our_history_and_passions', models.TextField(blank=True, null=True)),
                ('promo_video', models.FileField(upload_to='About us')),
                ('about_image', models.ImageField(upload_to='About us')),
            ],
        ),
        migrations.CreateModel(
            name='Basic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='About us')),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('office_address', models.TextField()),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('google_plus_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('date_and_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
