# Generated by Django 2.0.3 on 2018-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_aboutus_basic_info_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_text', models.CharField(blank=True, max_length=100, null=True)),
                ('big_text', models.CharField(max_length=100)),
                ('paragraph', models.CharField(max_length=250)),
                ('slide_image', models.ImageField(upload_to='Slider_Image')),
            ],
        ),
        migrations.AddField(
            model_name='basic_info',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singlevideo',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
