# Generated by Django 2.0.3 on 2018-03-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_course_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_public',
        ),
        migrations.AddField(
            model_name='singlevideo',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
