# Generated by Django 2.0.3 on 2018-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180320_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.CharField(default='March', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=3),
        ),
    ]
