# Generated by Django 2.0.3 on 2018-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180320_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='Course_Category'),
        ),
    ]
