# Generated by Django 2.0.3 on 2018-04-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180331_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_info',
            name='promo_video',
            field=models.FileField(blank=True, null=True, upload_to='Promo Video'),
        ),
    ]
