# Generated by Django 2.0.3 on 2018-04-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_basic_info_promo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlevideo',
            name='course_level',
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.CourseLevel'),
        ),
    ]
