# Generated by Django 2.0.3 on 2018-04-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180407_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='promo_video',
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='promo_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
