# Generated by Django 2.0.4 on 2018-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20180409_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery_image1',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image10',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image11',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image12',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image13',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image14',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image15',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image2',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image3',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image4',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image5',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image6',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image7',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image8',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image9',
            field=models.FileField(blank=True, null=True, upload_to='Events/Gallery'),
        ),
    ]
