# Generated by Django 2.0.4 on 2018-04-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180422_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gallery_image1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image10',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image11',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image12',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image13',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image14',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image15',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image4',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image5',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image6',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image7',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image8',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gallery_image9',
        ),
    ]
