# Generated by Django 2.0.3 on 2018-04-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180424_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image2',
            field=models.FileField(blank=True, upload_to='Gallery/events'),
        ),
    ]
