# Generated by Django 2.0.3 on 2018-04-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20180426_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image9',
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image1',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image10',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image11',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image12',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image2',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image3',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image4',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image5',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image6',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image7',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image8',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_image9',
            field=models.FileField(blank=True, null=True, upload_to='Gallery/events'),
        ),
    ]
